[package]
name = "xmr-varint"
version = "0.1.0"
authors = ["Jean Pierre Dudey <jeandudey@hotmail.com>"]
license = "MIT/Apache-2.0"
include = ["LICENSE-APACHE", "LICENSE-MIT"]

[dependencies]
bytes = "0.4.6"
num = "0.1.41"
